const boardEventList = [
    'object:modified',
    'object:rotated',
    'object:scaled',
    'object:moved',
    'object:skewed',
    'object:rotating',
    'object:scaling',
    'object:moving',
    'object:skewing',
    'before:transform',
    'before:selection:cleared',
    'selection:cleared',
    'selection:updated',
    'selection:created',
    'path:created',
    'mouse:down',
    'mouse:move',
    'mouse:up',
    'mouse:down:before',
    'mouse:move:before',
    'mouse:up:before',
    'mouse:over',
    'mouse:out',
    'mouse:dblclick',
    'event:dragover',
    'event:dragenter',
    'event:dragleave',
    'event:drop',
    'object:added',
    'object:removed',
];

export default {
    boardEventList,
};
